<table border="1">
<thead>
<tr>
<th>#</th>
<th>Nombre</th>
<th>Precio</th>
<th>Stock</th>
<th>Comprar</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Zapatilllas</td>
<td>200.00</td>
<td>2</td>
<td><a href="EJERCICIO_1.PHP?id=1">AGREGAR</a></td>
</tr>
<tr>
<td>2</td>
<td>Pelotas</td>
<td>60.00</td>
<td>5</td>
<td><a href="EJERCICIO_1.PHP?id=2">AGREGAR</a></td>
</tr>
<tr>
<td>3</td>
<td>Polo</td>
<td>80.00</td>
<td>10</td>
<td><a href="EJERCICIO_1.PHP?id=3">AGREGAR</a></td>
</tr>
</tbody>
</table>